version: 2

defaults: &defaults
  working_directory: ~/app
  environment:
    JAVA_OPTS: -XX:+AggressiveOpts -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+CMSClassUnloadingEnabled -XX:ReservedCodeCacheSize=128m -XX:SurvivorRatio=128 -XX:MaxTenuringThreshold=0 -XX:-EliminateAutoBox -Xms512M -Xmx1280M
  docker:
    - image: circleci/openjdk:8-jdk

references:
  workspace_root: &workspace_root
    ./

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_dependency_cache: &restore_dependency_cache
    restore_cache:
      name: Restore dependency cache
      keys:
        # try exact match for current branch and build.sbt checksum
        - v2-cache-dependencies-{{ .Branch }}-{{ checksum "build.sbt" }}
        # try master with matching build.sbt checksum
        - v2-cache-dependencies-master-{{ checksum "build.sbt" }}
        # try most recent for current branch
        - v2-cache-dependencies-{{ .Branch }}
        # fallback to most recent master
        - v2-cache-dependencies-master
  restore_target_cache: &restore_target_cache
    restore_cache:
      name: Restore build cache
      keys:
        # try exact match for current branch and git revision
        - v2-cache-build-{{ .Branch }}-{{ .Revision }}
        # try most recent for current branch
        - v2-cache-build-{{ .Branch }}
        # fallback to most recent on master
        - v2-cache-build-master

  save_dependency_cache: &save_dependency_cache
    save_cache:
      name: Save dependency cache
      key: v2-cache-dependencies-{{ .Branch }}-{{ checksum "build.sbt" }}
      paths:
        - ~/.ivy2
        - ~/.sbt
        - ~/.m2
        - ~/.cache/coursier
        - ~/.coursier

  save_target_cache: &save_target_cache
    save_cache:
      name: Save target cache
      key: v2-cache-build-{{ .Branch }}-{{ .Revision }}
      paths:
        - target
        - project/target
        - modulea/target
        - moduleb/target

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # - *restore_dependency_cache
      # - *restore_target_cache

      - run:
          name: Build project
          command: |
            sbt compile test:compile

      - run:
          name: Show file system
          command: |
            find /

      # Cleanup cache directories
      - run:
          name: Cleanup cache directories
          command: |
            find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete || true
            find $HOME/.sbt/cache -name "*.lock" -print -delete || true
            find $HOME/.cache/coursier -name "ivydata-*.properties" -print -delete || true
            find $HOME/.coursier -name "ivydata-*.properties" -print -delete || true

      # - *save_dependency_cache
      # - *save_target_cache

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  tests:
    <<: *defaults

    steps:
      - *attach_workspace
      # - *restore_dependency_cache

      - run:
          name: Run tests
          command: |
            sbt modulea/test moduleb/test

  docker_stage_moduleb:
    <<: *defaults

    steps:
      - *attach_workspace
      # - *restore_dependency_cache

      # Build and save caches.
      - run:
          name: Run moduleb
          command: |
            sbt moduleb/run

      # - persist_to_workspace:
      #     root: *workspace_root
      #     paths:
      #       - moduleb/target/docker/stage/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - docker_stage_moduleb:
          requires:
            - build
