version: 2

defaults: &defaults
  working_directory: ~/app
  environment:
    JAVA_OPTS: -XX:+AggressiveOpts -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+CMSClassUnloadingEnabled -XX:ReservedCodeCacheSize=128m -XX:SurvivorRatio=128 -XX:MaxTenuringThreshold=0 -XX:-EliminateAutoBox -Xms512M -Xmx1280M
  docker:
    - image: circleci/openjdk:8-jdk

references:
  workspace_root: &workspace_root
    ./

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  save_sbt_cache: &save_sbt_cache
    save_cache:
      name: Save SBT cache
      key: v3-cache-sbt-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/.sbt

  save_dependency_cache: &save_dependency_cache
    save_cache:
      name: Save dependency cache
      key: v3-cache-dependencies-{{ .Branch }}-{{ checksum "build.sbt" }}
      paths:
        - ~/.ivy2

  save_app_target_cache: &save_app_target_cache
    save_cache:
      name: Save app target cache
      key: v3-cache-build-app-{{ .Branch }}-{{ .Revision }}
      paths:
        - modulea/target
        - moduleb/target

  save_project_target_cache: &save_project_target_cache
    save_cache:
      name: Save project target cache
      key: v3-cache-build-project-{{ .Branch }}-{{ .Revision }}
      paths:
        - project/target
        - target

  restore_sbt_cache: &restore_sbt_cache
    restore_cache:
      name: Restores SBT cache
      keys:
        - v3-cache-sbt-{{ .Branch }}-{{ .Revision }}
        - v3-cache-sbt-{{ .Branch }}-
        - v3-cache-sbt-master

  restore_dependency_cache: &restore_dependency_cache
    restore_cache:
      name: Restore dependency cache
      keys:
        # try exact match for current branch and build.sbt checksum
        - v3-cache-dependencies-{{ .Branch }}-{{ checksum "build.sbt" }}
        # try master with matching build.sbt checksum
        - v3-cache-dependencies-master-{{ checksum "build.sbt" }}
        # try most recent for current branch
        - v3-cache-dependencies-{{ .Branch }}-
        # fallback to most recent master
        - v3-cache-dependencies-master

  restore_app_target_cache: &restore_app_target_cache
    restore_cache:
      name: Restore app build cache
      keys:
        # try exact match for current branch and git revision
        - v3-cache-build-app-{{ .Branch }}-{{ .Revision }}
        # try most recent for current branch
        - v3-cache-build-app-{{ .Branch }}-
        # fallback to most recent on master
        - v3-cache-build-app-master

  restore_project_target_cache: &restore_project_target_cache
    restore_cache:
      name: Restore project build cache
      keys:
        # try exact match for current branch and git revision
        - v3-cache-build-project-{{ .Branch }}-{{ .Revision }}
        # try most recent for current branch
        - v3-cache-build-project-{{ .Branch }}-
        # fallback to most recent on master
        - v3-cache-build-project-master

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - *restore_sbt_cache
      - *restore_dependency_cache
      - *restore_project_target_cache
      - *restore_app_target_cache

      - run:
          name: Build project
          command: |
            sbt compile test:compile modulea/compile modulea/test:compile moduleb/compile moduleb/test:compile

      - run:
          name: Show file system
          command: |
            find ~/

      # Cleanup cache directories
      - run:
          name: Cleanup cache directories
          command: |
            find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete || true
            find $HOME/.sbt -name "*.lock" -print -delete || true

      - *save_sbt_cache
      - *save_dependency_cache
      - *save_project_target_cache
      - *save_app_target_cache

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  tests:
    <<: *defaults

    steps:
      - *attach_workspace

      - *restore_sbt_cache
      - *restore_dependency_cache
      - *restore_project_target_cache
      - *restore_app_target_cache

      - run:
          name: Run tests
          command: |
            sbt modulea/test moduleb/test

  docker_stage_moduleb:
    <<: *defaults

    steps:
      - *attach_workspace

      - *restore_sbt_cache
      - *restore_dependency_cache
      - *restore_project_target_cache
      - *restore_app_target_cache

      # Build and save caches.
      - run:
          name: Run moduleb
          command: |
            sbt moduleb/run

      # - persist_to_workspace:
      #     root: *workspace_root
      #     paths:
      #       - moduleb/target/docker/stage/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - docker_stage_moduleb:
          requires:
            - build
